// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/openshift/api/monitoring/v1alpha1"
	monitoringv1alpha1 "github.com/openshift/client-go/monitoring/applyconfigurations/monitoring/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeObservabilityDataExports implements ObservabilityDataExportInterface
type FakeObservabilityDataExports struct {
	Fake *FakeMonitoringV1alpha1
	ns   string
}

var observabilitydataexportsResource = v1alpha1.SchemeGroupVersion.WithResource("observabilitydataexports")

var observabilitydataexportsKind = v1alpha1.SchemeGroupVersion.WithKind("ObservabilityDataExport")

// Get takes name of the observabilityDataExport, and returns the corresponding observabilityDataExport object, and an error if there is any.
func (c *FakeObservabilityDataExports) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ObservabilityDataExport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(observabilitydataexportsResource, c.ns, name), &v1alpha1.ObservabilityDataExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ObservabilityDataExport), err
}

// List takes label and field selectors, and returns the list of ObservabilityDataExports that match those selectors.
func (c *FakeObservabilityDataExports) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ObservabilityDataExportList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(observabilitydataexportsResource, observabilitydataexportsKind, c.ns, opts), &v1alpha1.ObservabilityDataExportList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ObservabilityDataExportList{ListMeta: obj.(*v1alpha1.ObservabilityDataExportList).ListMeta}
	for _, item := range obj.(*v1alpha1.ObservabilityDataExportList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested observabilityDataExports.
func (c *FakeObservabilityDataExports) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(observabilitydataexportsResource, c.ns, opts))

}

// Create takes the representation of a observabilityDataExport and creates it.  Returns the server's representation of the observabilityDataExport, and an error, if there is any.
func (c *FakeObservabilityDataExports) Create(ctx context.Context, observabilityDataExport *v1alpha1.ObservabilityDataExport, opts v1.CreateOptions) (result *v1alpha1.ObservabilityDataExport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(observabilitydataexportsResource, c.ns, observabilityDataExport), &v1alpha1.ObservabilityDataExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ObservabilityDataExport), err
}

// Update takes the representation of a observabilityDataExport and updates it. Returns the server's representation of the observabilityDataExport, and an error, if there is any.
func (c *FakeObservabilityDataExports) Update(ctx context.Context, observabilityDataExport *v1alpha1.ObservabilityDataExport, opts v1.UpdateOptions) (result *v1alpha1.ObservabilityDataExport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(observabilitydataexportsResource, c.ns, observabilityDataExport), &v1alpha1.ObservabilityDataExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ObservabilityDataExport), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeObservabilityDataExports) UpdateStatus(ctx context.Context, observabilityDataExport *v1alpha1.ObservabilityDataExport, opts v1.UpdateOptions) (*v1alpha1.ObservabilityDataExport, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(observabilitydataexportsResource, "status", c.ns, observabilityDataExport), &v1alpha1.ObservabilityDataExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ObservabilityDataExport), err
}

// Delete takes name of the observabilityDataExport and deletes it. Returns an error if one occurs.
func (c *FakeObservabilityDataExports) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(observabilitydataexportsResource, c.ns, name, opts), &v1alpha1.ObservabilityDataExport{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeObservabilityDataExports) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(observabilitydataexportsResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ObservabilityDataExportList{})
	return err
}

// Patch applies the patch and returns the patched observabilityDataExport.
func (c *FakeObservabilityDataExports) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ObservabilityDataExport, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(observabilitydataexportsResource, c.ns, name, pt, data, subresources...), &v1alpha1.ObservabilityDataExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ObservabilityDataExport), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied observabilityDataExport.
func (c *FakeObservabilityDataExports) Apply(ctx context.Context, observabilityDataExport *monitoringv1alpha1.ObservabilityDataExportApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ObservabilityDataExport, err error) {
	if observabilityDataExport == nil {
		return nil, fmt.Errorf("observabilityDataExport provided to Apply must not be nil")
	}
	data, err := json.Marshal(observabilityDataExport)
	if err != nil {
		return nil, err
	}
	name := observabilityDataExport.Name
	if name == nil {
		return nil, fmt.Errorf("observabilityDataExport.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(observabilitydataexportsResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.ObservabilityDataExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ObservabilityDataExport), err
}

// ApplyStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating ApplyStatus().
func (c *FakeObservabilityDataExports) ApplyStatus(ctx context.Context, observabilityDataExport *monitoringv1alpha1.ObservabilityDataExportApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.ObservabilityDataExport, err error) {
	if observabilityDataExport == nil {
		return nil, fmt.Errorf("observabilityDataExport provided to Apply must not be nil")
	}
	data, err := json.Marshal(observabilityDataExport)
	if err != nil {
		return nil, err
	}
	name := observabilityDataExport.Name
	if name == nil {
		return nil, fmt.Errorf("observabilityDataExport.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(observabilitydataexportsResource, c.ns, *name, types.ApplyPatchType, data, "status"), &v1alpha1.ObservabilityDataExport{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ObservabilityDataExport), err
}
